import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Image } from "expo-image";
import { router } from "expo-router";
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { useAuth } from "@/hooks/use-auth";
import { resolveAssetUrl } from "@/lib/assets";
import { trpc } from "@/lib/trpc";

const statusMeta: Record<string, { label: string; color: string; tint: string; icon: keyof typeof MaterialIcons.glyphMap }> = {
  pending: { label: "მოლოდინში", color: "#A85C00", tint: "#FFF0D4", icon: "schedule" },
  confirmed: { label: "დადასტურებული", color: "#7057D9", tint: "#EEE8FF", icon: "check-circle" },
  preparing: { label: "მზადდება", color: "#286D9D", tint: "#E6F4FE", icon: "inventory" },
  shipped: { label: "გაგზავნილია", color: "#236B51", tint: "#E7F5EF", icon: "local-shipping" },
  delivered: { label: "ჩაბარებულია", color: "#39745D", tint: "#E7F5EF", icon: "task-alt" },
  cancelled: { label: "გაუქმებულია", color: "#9A4B5B", tint: "#FBE2E8", icon: "cancel" },
};

const shellText = StyleSheet.create({
  title: { color: "#F7F9FF" },
  body: { color: "#C5D5FF" },
});

export default function CustomerOrdersScreen() {
  const { isAuthenticated, startLogin } = useAuth();
  const { data: orders = [], isLoading } = trpc.orders.customerList.useQuery(undefined, { enabled: isAuthenticated, retry: 1, staleTime: 10_000 });
  if (!isAuthenticated) return <ScreenContainer><View style={styles.center}><View style={styles.emptyIcon}><MaterialIcons name="lock-outline" size={35} color="#7057D9" /></View><Text style={[styles.emptyTitle, shellText.title]}>შეკვეთები ანგარიშით იხსნება</Text><Text style={[styles.emptyText, shellText.body]}>შედი ანგარიშში, რათა შენი ტრანზაქციები და სტატუსები ნახო.</Text><Pressable onPress={() => void startLogin()} style={({ pressed }) => [styles.loginButton, pressed && styles.pressed]}><Text style={styles.loginText}>რეგისტრაცია ან შესვლა</Text></Pressable></View></ScreenContainer>;
  return <ScreenContainer><FlatList data={orders} keyExtractor={(item) => String(item.id)} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} ItemSeparatorComponent={() => <View style={styles.separator} />} ListHeaderComponent={<View style={styles.header}><View style={styles.headerTop}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><MaterialIcons name="arrow-back-ios-new" size={20} color="#251F24" /></Pressable><Text style={[styles.title, shellText.title]}>ჩემი შეკვეთები</Text><View style={styles.headerSpacer} /></View><Text style={[styles.subtitle, shellText.body]}>აქ ნახავ ყველა გადახდილ შეკვეთას და მის მიმდინარე სტატუსს.</Text></View>} renderItem={({ item }) => <CustomerOrderCard order={item} />} ListEmptyComponent={isLoading ? <ActivityIndicator color="#E94F6D" style={styles.loader} /> : <View style={styles.empty}><View style={styles.emptyIcon}><MaterialIcons name="receipt-long" size={37} color="#7057D9" /></View><Text style={[styles.emptyTitle, shellText.title]}>შეკვეთები ჯერ არ გაქვს</Text><Text style={[styles.emptyText, shellText.body]}>როცა პროდუქტს შეიძენ, მისი ტრანზაქცია და სტატუსი აქ გამოჩნდება.</Text></View>} /></ScreenContainer>;
}

function CustomerOrderCard({ order }: { order: { id: number; productName: string; productImageUrl: string; businessName: string; businessCity: string | null; quantity: number; customerTotalInTetri: number; customerPaymentFeeInTetri: number; paymentReference: string | null; paymentStatus: string; deliveryAddress: string; status: string; createdAt: Date | string } }) {
  const meta = statusMeta[order.status] ?? statusMeta.pending;
  return <View style={styles.card}><View style={styles.cardHeader}><View><Text style={styles.orderId}>შეკვეთა #{order.id}</Text><Text style={styles.date}>{new Date(order.createdAt).toLocaleDateString("ka-GE", { year: "numeric", month: "long", day: "numeric" })}</Text></View><View style={[styles.status, { backgroundColor: meta.tint }]}><MaterialIcons name={meta.icon} size={14} color={meta.color} /><Text style={[styles.statusText, { color: meta.color }]}>{meta.label}</Text></View></View><View style={styles.productRow}><Image source={resolveAssetUrl(order.productImageUrl)} contentFit="cover" style={styles.image} /><View style={styles.productCopy}><Text style={styles.business}>{order.businessName}</Text><Text style={styles.productName}>{order.productName}</Text><Text style={styles.detail}>{order.quantity} ერთეული · {order.businessCity ?? "საქართველო"}</Text></View></View><View style={styles.totalBox}><View><Text style={styles.totalLabel}>გადახდილი თანხა</Text><Text style={styles.totalHint}>მომსახურება: {(order.customerPaymentFeeInTetri / 100).toFixed(2)} ₾</Text></View><Text style={styles.total}>{(order.customerTotalInTetri / 100).toFixed(2)} ₾</Text></View><View style={styles.delivery}><MaterialIcons name="location-on" size={16} color="#8C7F85" /><Text style={styles.deliveryText}>{order.deliveryAddress}</Text></View>{order.paymentReference ? <Text style={styles.reference}>ტრანზაქცია: {order.paymentReference}</Text> : null}</View>;
}

const styles = StyleSheet.create({ content: { flexGrow: 1, paddingHorizontal: 20, paddingBottom: 32 }, header: { gap: 10, paddingBottom: 18 }, headerTop: { height: 48, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, back: { width: 42, height: 42, borderRadius: 21, alignItems: "center", justifyContent: "center", backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EADFDA" }, title: { color: "#251F24", fontSize: 18, lineHeight: 24, fontWeight: "900" }, headerSpacer: { width: 42 }, subtitle: { color: "#756B70", fontSize: 13, lineHeight: 19 }, separator: { height: 12 }, card: { gap: 12, padding: 15, borderRadius: 22, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EADFDA" }, cardHeader: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 10 }, orderId: { color: "#251F24", fontSize: 14, lineHeight: 19, fontWeight: "900" }, date: { color: "#8C7F85", fontSize: 11, lineHeight: 16 }, status: { flexDirection: "row", alignItems: "center", gap: 4, borderRadius: 11, paddingHorizontal: 8, paddingVertical: 5 }, statusText: { fontSize: 10, lineHeight: 14, fontWeight: "800" }, productRow: { flexDirection: "row", gap: 11 }, image: { width: 62, height: 62, borderRadius: 16, backgroundColor: "#F7EAE5" }, productCopy: { flex: 1, justifyContent: "center", gap: 2 }, business: { color: "#7057D9", fontSize: 11, lineHeight: 15, fontWeight: "800" }, productName: { color: "#3D353A", fontSize: 15, lineHeight: 20, fontWeight: "800" }, detail: { color: "#8C7F85", fontSize: 11, lineHeight: 16 }, totalBox: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", padding: 12, borderRadius: 16, backgroundColor: "#E7F5EF" }, totalLabel: { color: "#39745D", fontSize: 11, lineHeight: 15, fontWeight: "800" }, totalHint: { color: "#5F8B77", fontSize: 10, lineHeight: 14 }, total: { color: "#236B51", fontSize: 18, lineHeight: 24, fontWeight: "900" }, delivery: { flexDirection: "row", alignItems: "flex-start", gap: 6 }, deliveryText: { flex: 1, color: "#756B70", fontSize: 12, lineHeight: 17 }, reference: { color: "#A79CA1", fontSize: 10, lineHeight: 14 }, center: { flex: 1, alignItems: "center", justifyContent: "center", paddingHorizontal: 30, gap: 9 }, empty: { alignItems: "center", justifyContent: "center", paddingHorizontal: 30, paddingVertical: 64, gap: 9 }, emptyIcon: { width: 70, height: 70, borderRadius: 23, alignItems: "center", justifyContent: "center", backgroundColor: "#EEE8FF" }, emptyTitle: { color: "#251F24", fontSize: 19, lineHeight: 25, fontWeight: "900", textAlign: "center" }, emptyText: { color: "#756B70", fontSize: 13, lineHeight: 19, textAlign: "center" }, loginButton: { marginTop: 6, minHeight: 45, paddingHorizontal: 17, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: "#E94F6D" }, loginText: { color: "#FFFFFF", fontSize: 14, lineHeight: 19, fontWeight: "800" }, loader: { marginTop: 64 }, pressed: { opacity: 0.68 } });
